name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  library:
    runs-on: macos-latest
    strategy:
      matrix:
        platform: 
          - iOS Simulator,name=iPhone 14 Pro Max
          - macOS
          - tvOS Simulator,name=Apple TV
          - watchOS Simulator,name=Apple Watch Series 7 (45mm)

    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: PLATFORM="${{ matrix.platform }}" make test-library
